#!/bin/sh /etc/rc.common
# 
# Setup environment
#
# Huanle Zhang at UC Davis
# www.huanlezhang.com

# last start
START=z0
# first stop 
STOP=000z

start(){
	
	dtcRoot="/dtcRoot"
	dtcBackupDir="${dtcRoot}/backup"
	dtcDebugDir="${dtcRoot}/debug"
	dtcEnvFile="${dtcRoot}/dtcEnvironmentSetup"
	dtcTmp="/tmp/dtc"

	# tmp folder for dtc
	mkdir -p $dtcTmp

	# clear debug files
	cat /dev/null > ${dtcDebugDir}/environment

	echo "$(date) dtc_environment START" > ${dtcDebugDir}/environment

	# change ash to bash
	if [ -x "/bin/bash" ]; then
		# only if bash exist
		sed -i -e 's#/root:/bin/ash#/root:/bin/bash#' /etc/passwd 
	else
		echo "$(date) *** dtc_environment /bin/bash does not exist" >> ${dtcDebugDir}/environment 
	fi 

	
	if [ ! -f "${dtcBackupDir}/etc/profile" ]; then

		# /etc/profile
		mkdir -p ${dtcBackupDir}/etc/
		cp -p /etc/profile ${dtcBackupDir}/etc/profile
		
		# /etc/config/network
		mkdir -p ${dtcBackupDir}/etc/config/
		cp -p /etc/config/network ${dtcBackupDir}/etc/config/network
		
		# /etc/config/system
		mkdir -p ${dtcBackupDir}/etc/config/
		cp -p /etc/config/system ${dtcBackupDir}/etc/config/system 

		# commands in the file of ${dtcEnvFile}
		cat ${dtcEnvFile} >> /etc/profile 
	fi 
}

stop(){
	echo "$(date) dtc_environment STOP" >> ${dtcDebugDir}/environment 
}
